In [1]:
import pandas as pd
pd.__version__

'2.3.3'

### Series
A Series is like a single column of data—just one axis.
Think of it as a simple list or array

Unlike a plain list or a NumPy array, each value in a Series has a label, called an index

This labeling allows you to access data by name instead of just position:

By position → series[0]
By label → series['a']

In [2]:
# Series - 1D labeled array
series = pd.Series([10, 20, 30, 40, 50])
print("Series with default index:")
print(series)
print(series[3])

Series with default index:
0    10
1    20
2    30
3    40
4    50
dtype: int64
40

In [3]:

# Series with custom index
series_custom = pd.Series([10, 20, 30, 40, 50], index=[44, 33, 'c', 'd', 'e'])
print("\nSeries with custom index:") # once custom index is assigned, default index get overwritten.
print(series_custom)
print(series_custom[33], series_custom['c'])

Series with custom index:
44    10
33    20
c     30
d     40
e     50
dtype: int64
20 30

In [4]:
# Series from dictionary
series_dict = pd.Series({'apple': 5, 'banana': 10, 'orange': 7, 'grape': 12})
print("\nSeries from dictionary:")
print(series_dict)
print(series_dict['banana'])
print(series_dict.iloc[1]) # even after assigning custom index, we can access values via position using iloc.

Series from dictionary:
apple      5
banana    10
orange     7
grape     12
dtype: int64
10
10

In [5]:
# Series operations
series = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])

print("Original series:")
print(series)

print("\nAccess by label (series['b']):", series['b'])
# print("Access by position (series[1]):", series[1])

print("\nSeries + 5:")
print(series + 5)

print("\nSeries * 2:")
print(series * 2)

print("\nSeries properties:")
print("Values:", series.values)
print("Index:", series.index)
print("Name:", series.name)

Original series:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Access by label (series['b']): 20

Series + 5:
a    15
b    25
c    35
d    45
e    55
dtype: int64

Series * 2:
a     20
b     40
c     60
d     80
e    100
dtype: int64

Series properties:
Values: [10 20 30 40 50]
Index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Name: None

In [6]:
# DataFrame - 2D labeled data structure
# Creating from dictionary
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], # each columns and their values are represented as key-value pairs in the dictionary.
    'age': [25, 30, 35, 28, 32],
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin'],
    'salary': [70000, 80000, 75000, 65000, 72000]
}

df = pd.DataFrame(data)
print("DataFrame from dictionary:")
print(df)

DataFrame from dictionary:
      name  age      city  salary
0    Alice   25  New York   70000
1      Bob   30    London   80000
2  Charlie   35     Paris   75000
3    David   28     Tokyo   65000
4      Eve   32    Berlin   72000

In [7]:
# creating Dataframe from a list of lists
data_list = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'London'],
    ['Charlie', 35, 'Paris']
]

pd.DataFrame(data_list, columns=['name', 'age', 'city'])

      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [8]:
df = pd.read_csv("./abc.csv") # read_csv() method is used to read a CSV file and create a DataFrame from it.

In [9]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize: 'bool' = False, name: 'Hashable | None' = None, inclusive: 'IntervalClosedType' = 'both', *, unit: 'str | None' = None, **kwargs) -> 'DatetimeIndex'
    Return a fixed frequency DatetimeIndex.

    Returns the range of equally spaced time points (where the difference between any
    two adjacent points is specified by the given frequency) such that they all
    satisfy `start <[=] x <[=] end`, where the first one and the last one are, resp.,
    the first and last time points in that range that fall on the boundary of ``freq``
    (if given as a frequency string) or that are valid for ``freq`` (if given as a
    :class:`pandas.tseries.offsets.DateOffset`). (If exactly one of ``start``,
    ``end``, or ``freq`` is *not* specified, this missing parameter can be computed
    given ``periods``, the number of timesteps in the range. See the note below.)

    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str, Timedelta, datetime.timedelta, or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5h'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive unless timezone-aware datetime-likes are passed.
    normalize : bool, default False
        Normalize start/end dates to midnight before generating date range.
    name : str, default None
        Name of the resulting DatetimeIndex.
    inclusive : {"both", "neither", "left", "right"}, default "both"
        Include boundaries; Whether to set each bound as closed or open.

        .. versionadded:: 1.4.0
    unit : str, default None
        Specify the desired resolution of the result.

        .. versionadded:: 2.0.0
    **kwargs
        For compatibility. Has no effect on the result.

    Returns
    -------
    DatetimeIndex

    See Also
    --------
    DatetimeIndex : An immutable container for datetimes.
    timedelta_range : Return a fixed frequency TimedeltaIndex.
    period_range : Return a fixed frequency PeriodIndex.
    interval_range : Return a fixed frequency IntervalIndex.

    Notes
    -----
    Of the four parameters ``start``, ``end``, ``periods``, and ``freq``,
    exactly three must be specified. If ``freq`` is omitted, the resulting
    ``DatetimeIndex`` will have ``periods`` linearly spaced elements between
    ``start`` and ``end`` (closed on both sides).

    To learn more about the frequency strings, please see `this link
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases>`__.

    Examples
    --------
    **Specifying the values**

    The next four examples generate the same `DatetimeIndex`, but vary
    the combination of `start`, `end` and `periods`.

    Specify `start` and `end`, with the default daily frequency.

    >>> pd.date_range(start='1/1/2018', end='1/08/2018')
    DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
                   '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
                  dtype='datetime64[ns]', freq='D')

    Specify timezone-aware `start` and `end`, with the default daily frequency.

    >>> pd.date_range(
    ...     start=pd.to_datetime("1/1/2018").tz_localize("Europe/Berlin"),
    ...     end=pd.to_datetime("1/08/2018").tz_localize("Europe/Berlin"),
    ... )
    DatetimeIndex(['2018-01-01 00:00:00+01:00', '2018-01-02 00:00:00+01:00',
                   '2018-01-03 00:00:00+01:00', '2018-01-04 00:00:00+01:00',
                   '2018-01-05 00:00:00+01:00', '2018-01-06 00:00:00+01:00',
                   '2018-01-07 00:00:00+01:00', '2018-01-08 00:00:00+01:00'],
                  dtype='datetime64[ns, Europe/Berlin]', freq='D')

    Specify `start` and `periods`, the number of periods (days).

    >>> pd.date_range(start='1/1/2018', periods=8)
    DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
                   '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
                  dtype='datetime64[ns]', freq='D')

    Specify `end` and `periods`, the number of periods (days).

    >>> pd.date_range(end='1/1/2018', periods=8)
    DatetimeIndex(['2017-12-25', '2017-12-26', '2017-12-27', '2017-12-28',
                   '2017-12-29', '2017-12-30', '2017-12-31', '2018-01-01'],
                  dtype='datetime64[ns]', freq='D')

    Specify `start`, `end`, and `periods`; the frequency is generated
    automatically (linearly spaced).

    >>> pd.date_range(start='2018-04-24', end='2018-04-27', periods=3)
    DatetimeIndex(['2018-04-24 00:00:00', '2018-04-25 12:00:00',
                   '2018-04-27 00:00:00'],
                  dtype='datetime64[ns]', freq=None)

    **Other Parameters**

    Changed the `freq` (frequency) to ``'ME'`` (month end frequency).

    >>> pd.date_range(start='1/1/2018', periods=5, freq='ME')
    DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
                   '2018-05-31'],
                  dtype='datetime64[ns]', freq='ME')

    Multiples are allowed

    >>> pd.date_range(start='1/1/2018', periods=5, freq='3ME')
    DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
                   '2019-01-31'],
                  dtype='datetime64[ns]', freq='3ME')

    `freq` can also be specified as an Offset object.

    >>> pd.date_range(start='1/1/2018', periods=5, freq=pd.offsets.MonthEnd(3))
    DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
                   '2019-01-31'],
                  dtype='datetime64[ns]', freq='3ME')

    Specify `tz` to set the timezone.

    >>> pd.date_range(start='1/1/2018', periods=5, tz='Asia/Tokyo')
    DatetimeIndex(['2018-01-01 00:00:00+09:00', '2018-01-02 00:00:00+09:00',
                   '2018-01-03 00:00:00+09:00', '2018-01-04 00:00:00+09:00',
                   '2018-01-05 00:00:00+09:00'],
                  dtype='datetime64[ns, Asia/Tokyo]', freq='D')

    `inclusive` controls whether to include `start` and `end` that are on the
    boundary. The default, "both", includes boundary points on either end.

    >>> pd.date_range(start='2017-01-01', end='2017-01-04', inclusive="both")
    DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04'],
                  dtype='datetime64[ns]', freq='D')

    Use ``inclusive='left'`` to exclude `end` if it falls on the boundary.

    >>> pd.date_range(start='2017-01-01', end='2017-01-04', inclusive='left')
    DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03'],
                  dtype='datetime64[ns]', freq='D')

    Use ``inclusive='right'`` to exclude `start` if it falls on the boundary, and
    similarly ``inclusive='neither'`` will exclude both `start` and `end`.

    >>> pd.date_range(start='2017-01-01', end='2017-01-04', inclusive='right')
    DatetimeIndex(['2017-01-02', '2017-01-03', '2017-01-04'],
                  dtype='datetime64[ns]', freq='D')

    **Specify a unit**

    >>> pd.date_range(start="2017-01-01", periods=10, freq="100YS", unit="s")
    DatetimeIndex(['2017-01-01', '2117-01-01', '2217-01-01', '2317-01-01',
                   '2417-01-01', '2517-01-01', '2617-01-01', '2717-01-01',
                   '2817-01-01', '2917-01-01'],
                  dtype='datetime64[s]', freq='100YS-JAN')

# Question : create 10 dates and assign them to a column

In [10]:
data = {
    'datetime_col': pd.date_range('2024-01-01', periods=10, freq="ME")# returns an array of 10 data numbers
}
# freq take values h , d , y , ME , incrementing the dates by hour, day , year and month

pd.DataFrame(data) # Date in pandas

  datetime_col
0   2024-01-31
1   2024-02-29
2   2024-03-31
3   2024-04-30
4   2024-05-31
5   2024-06-30
6   2024-07-31
7   2024-08-31
8   2024-09-30
9   2024-10-31

In [11]:
# Get concise summary of the DataFrame
print("DataFrame Info:")
df.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   student   7 non-null      object
 1   language  7 non-null      int64
 2   science   7 non-null      int64
 3   maths     7 non-null      int64
 4   history   7 non-null      int64
dtypes: int64(4), object(1)
memory usage: 408.0+ bytes

In [12]:
# Statistical summary of numerical columns
print("Descriptive statistics for numerical columns:")
print(df.describe())

Descriptive statistics for numerical columns:
        language    science      maths    history
count   7.000000   7.000000   7.000000   7.000000
mean   54.285714  53.000000  43.285714  42.857143
std    35.523299  22.015146  23.746679  17.062909
min    10.000000  23.000000  12.000000  23.000000
25%    25.000000  39.500000  33.000000  33.000000
50%    50.000000  56.000000  45.000000  34.000000
75%    90.000000  61.500000  45.000000  55.000000
max    90.000000  90.000000  90.000000  67.000000

In [13]:
print("Descriptive statistics for numerical columns:")
print(df.describe(include='all')) # include all columns, including non-numeric ones.

Descriptive statistics for numerical columns:
       student   language    science      maths    history
count        7   7.000000   7.000000   7.000000   7.000000
unique       7        NaN        NaN        NaN        NaN
top      kumar        NaN        NaN        NaN        NaN
freq         1        NaN        NaN        NaN        NaN
mean       NaN  54.285714  53.000000  43.285714  42.857143
std        NaN  35.523299  22.015146  23.746679  17.062909
min        NaN  10.000000  23.000000  12.000000  23.000000
25%        NaN  25.000000  39.500000  33.000000  33.000000
50%        NaN  50.000000  56.000000  45.000000  34.000000
75%        NaN  90.000000  61.500000  45.000000  55.000000
max        NaN  90.000000  90.000000  90.000000  67.000000

In [14]:
ser = pd.Series(["apple","banana","cherry","date","banana","apple","cherry","date","banana","apple"])

# display a column's values and their frequencies

In [15]:
ser.value_counts() # value_counts() method counts the occurrences of each unique value in a Series and returns a new Series with the counts.

apple     3
banana    3
cherry    2
date      2
Name: count, dtype: int64

In [16]:
df

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

# Question : Display the number of unique languages inside the column "language"

In [17]:
print(df["language"].nunique()) 
# nunique() method returns the number of unique values in a Series, useful for checking cardinality of a column.
print(df["student"].nunique())

5
7

In [18]:
pd.read_csv("./abc.csv",nrows=5) # read only first 5 rows of the CSV file.

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65

In [19]:
df[["student", "language"]].head() # select specific columns and display first 5 rows.

  student  language
0   kumar        90
1   kevin        10
2   sammy        90
3  janice        20
4   peter        30

In [20]:
# isin() operator
# works on Pandas Series object.
# returns a boolean mask series of len = len(series)

ser = pd.Series([1,2,3,4,5])
print(ser.isin([1,2]))

df[df["language"].isin([90,10])]

0     True
1     True
2    False
3    False
4    False
dtype: bool

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
5    prem        90       45     45       34

In [21]:
# iloc
# used to select columns and rows based on their positions

# Select rows and columns by position
print("\nFirst 5 rows, first 4 columns:")
print(df.iloc[0:5, 0:4])

print("\n" + "="*50)

# Select specific rows and columns by position
print("\nRows [0, 2, 4], columns [1, 3, 5]:")
print(df.iloc[[0, 2, 3], [0 ,2, 3]])

print("\n" + "="*50)

# Select every 100th row
print("\nEvery 100th row:")
print(df.iloc[::100, :5])

First 5 rows, first 4 columns:
  student  language  science  maths
0   kumar        90       56     34
1   kevin        10       34     32
2   sammy        90       23     12
3  janice        20       67     90
4   peter        30       56     45

==================================================

Rows [0, 2, 4], columns [1, 3, 5]:
  student  science  maths
0   kumar       56     34
2   sammy       23     12
3  janice       67     90

==================================================

Every 100th row:
  student  language  science  maths  history
0   kumar        90       56     34       34

In [22]:
# loc
# filters rows and columns, except this time columns can take their column_names


# Select specific rows and columns by label
print("\nRows 0-4, specific columns:")
print(df.loc[0:4, ["language","maths"]])

print("\n" + "="*50)

# Select rows based on condition
print("\nCustomers with age > 60:")
print(df.loc[df['language'] > 60, ["student","language"]].head())

print(df.loc[[0,2,3] , ["student","language"]])

Rows 0-4, specific columns:
   language  maths
0        90     34
1        10     32
2        90     12
3        20     90
4        30     45

==================================================

Customers with age > 60:
  student  language
0   kumar        90
2   sammy        90
5    prem        90
  student  language
0   kumar        90
2   sammy        90
3  janice        20

# Sort values of a column  and sort rows based on two columns

In [23]:
# Sorting a dataframe based on a single column
print(df.sort_values(["language"], ascending=False))
print("\n----------------------------\n")
# sorting based on multiple columns 
print(df.sort_values(["language","student"], ascending=[False, True])) # sorts by language first, if there are any ties in that sort, then it sorts based on student name alphabetically.

  student  language  science  maths  history
0   kumar        90       56     34       34
2   sammy        90       23     12       32
5    prem        90       45     45       34
6  carrol        50       90     45       23
4   peter        30       56     45       65
3  janice        20       67     90       45
1   kevin        10       34     32       67

----------------------------

  student  language  science  maths  history
0   kumar        90       56     34       34
5    prem        90       45     45       34
2   sammy        90       23     12       32
6  carrol        50       90     45       23
4   peter        30       56     45       65
3  janice        20       67     90       45
1   kevin        10       34     32       67

# Create a copy of a dataframe

In [24]:
# creating a df copy
df_copy = df.copy()
df_copy["student"] = "easdfklsjdf"
df_copy.head() , df.head()

(       student  language  science  maths  history
 0  easdfklsjdf        90       56     34       34
 1  easdfklsjdf        10       34     32       67
 2  easdfklsjdf        90       23     12       32
 3  easdfklsjdf        20       67     90       45
 4  easdfklsjdf        30       56     45       65,
   student  language  science  maths  history
 0   kumar        90       56     34       34
 1   kevin        10       34     32       67
 2   sammy        90       23     12       32
 3  janice        20       67     90       45
 4   peter        30       56     45       65)

In [25]:
df.duplicated() # returns a series boolean mask object,

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [26]:
df.rename(columns={"language":"english"}) # rename takes a dictionary of old column names and new column names and renames old ones.

  student  english  science  maths  history
0   kumar       90       56     34       34
1   kevin       10       34     32       67
2   sammy       90       23     12       32
3  janice       20       67     90       45
4   peter       30       56     45       65
5    prem       90       45     45       34
6  carrol       50       90     45       23

In [27]:
duplicated_df = pd.concat( (pd.DataFrame({
                "student":["kevin", "sammy"],
                "language":[10, 90],
                "science":[34, 23],
                "maths":[32,12],
                "history":[67,32]
            }, columns = df.columns), df) , axis = 0)

In [28]:
# It returns a Boolean Series (True/False values) indicating whether each row is a duplicate of a previous row.
# True → the row is a duplicate
# False → the row is unique (first occurrence)

duplicated_df.duplicated(keep = "last") # marks duplicated values as True, depending upon what we give as keep argument, it may mark the first occurence of duplicates as true or the last occurences

0     True
1     True
0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

# Drop Duplicates based on all the columns

In [29]:
duplicated_df.drop_duplicates(keep = "last")

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

# Drop duplicates based on Student and language columns

In [30]:
duplicated_df.drop_duplicates(subset=["student", "language"], keep = "first")
# the subset arguments lets you choose, the columns based on which two rows are considered to be duplicates.

  student  language  science  maths  history
0   kevin        10       34     32       67
1   sammy        90       23     12       32
0   kumar        90       56     34       34
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

# remove duplicates using duplicated()

In [31]:
# remove c
duplicated_df[~duplicated_df.duplicated(keep= "last")] # since, duplicates are marked as True, the condition needs to be inverted.

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

In [32]:
duplicated_df.dtypes

student     object
language     int64
science      int64
maths        int64
history      int64
dtype: object

# Question: casting columns to suitable types

In [33]:
# type conversions
duplicated_df["student"] = duplicated_df["student"].astype("category")
duplicated_df["language"] = duplicated_df["language"].astype("float32")
duplicated_df["maths"] = duplicated_df["maths"].astype("int32")
duplicated_df.dtypes
# type casting a object/string into category is a huge win.
# category, stores only n unique strings and their respective integer encodings
# and replaces these string values with integers behind the scenes.
# this is much more memory efficient than storing strings.
# operations such as Grouping , filtering becomes faster
# Category => Encoded + optimized representation.

student     category
language     float32
science        int64
maths          int32
history        int64
dtype: object

# Perform lower, upper, contains and starts with operations on Series Object

In [34]:
# String operations
df_string = pd.DataFrame({"student":["Kevin014", "Kiran", "Ritesh", "Suresh", "Vignesh","esh_esh_esh", "Rishkesh55", "vis4leshish", "veshnish"]})

# String methods
print("\nLowercase:")
print(df_string['student'].str.lower().head())

print("\nUppercase:")
print(df_string['student'].str.upper().head())

print("\nContains 'esh':")
print(df_string['student'].str.contains('esh').head())

print("\nStartswith 'k':")
print(df_string['student'].str.lower().str.startswith('k').sum(), "students")

Lowercase:
0    kevin014
1       kiran
2      ritesh
3      suresh
4     vignesh
Name: student, dtype: object

Uppercase:
0    KEVIN014
1       KIRAN
2      RITESH
3      SURESH
4     VIGNESH
Name: student, dtype: object

Contains 'esh':
0    False
1    False
2     True
3     True
4     True
Name: student, dtype: bool

Startswith 'k':
2 students

In [35]:
# print length of a string 
# replace a string with another in dataframe column

In [36]:
# More string operation
# String length

print("\nLength of student:")
print(df_string['student'].str.len())

Length of student:
0     8
1     5
2     6
3     6
4     7
5    11
6    10
7    11
8     8
Name: student, dtype: int64

In [37]:

# Replace in string
print("Replace 'esh' with 'ish")
print(df_string['student'].str.replace('esh', 'ish'))

Replace 'esh' with 'ish
0       Kevin014
1          Kiran
2         Ritish
3         Surish
4        Vignish
5    ish_ish_ish
6     Rishkish55
7    vis4lishish
8       vishnish
Name: student, dtype: object

In [38]:
# Extract numeric part
print("\nExtract numbers from customer_id:")
print(df_string['student'].str.extract(r'(\d+)'))

Extract numbers from customer_id:
     0
0  014
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6   55
7    4
8  NaN

In [39]:
# Split strings
print("\nSplit student by underscore:")
print(df_string['student'].str.split('_'))
print(df_string['student'].str.split('_').dtypes)

Split student by underscore:
0         [Kevin014]
1            [Kiran]
2           [Ritesh]
3           [Suresh]
4          [Vignesh]
5    [esh, esh, esh]
6       [Rishkesh55]
7      [vis4leshish]
8         [veshnish]
Name: student, dtype: object
object

In [40]:

# the split string could be access via indexing in this manner.
print(df_string['student'].str.split('_').str[0])

0       Kevin014
1          Kiran
2         Ritesh
3         Suresh
4        Vignesh
5            esh
6     Rishkesh55
7    vis4leshish
8       veshnish
Name: student, dtype: object

In [41]:

# df_datetime = pd.DataFrame()

# reference_date = pd.to_datetime('2024-01-01') # this is powerfull function in pandas , used to create date objects
# it can take up dates in multiple formats
# us - format mm/dd/yyyy
# iso - format yyyy-mm-dd
# text - format Apr 9, 2026

# its capable to taking this information from multiple columns as well.


reference_date = pd.to_datetime("1999-08-18", format=r"%Y-%m-%d") # note - Y -> takes 4 digit year, y - takes 2 digit year.

df_dates = pd.DataFrame({"day":["9", "28", "03", "14"], "month":["04","04","01","12"], "year":["2026","2014","2025","2023"]})
print(pd.to_datetime(df_dates[[ "month", "day", "year" ]])) # note - column names in the dataframe, at the time of inputting it to to_datetime should be named "day", "month", "year"


# # to avoid ambiguity , its best to specify the format , ie.
# print(pd.to_datetime("09-04-2026", format="%d-%m-%Y"))

# or you can use the dayfirst argument ie.
pd.to_datetime("09-04-2026", dayfirst=True) # here 09 is considered as day.

# differnce between two datatime objects
days_diff = pd.to_datetime(df_dates[[ "month", "day", "year" ]]) - reference_date
print( days_diff.iloc[[0]] )

duration = pd.to_timedelta(27*365, unit = "d") # here units can be d(days) , h(hours), m(minutes) , s(secs), ms(millis). timedelta returns a timedelta which is subtractable from datetime 
# note- months and years are excluded from the units due to ambiguity, since year can be 366 or 365 and the month can have 30 , 31, or 28 days.

print(days_diff.iloc[[0]]  - duration )
# df_datetime['join_date'] = reference_date - pd.to_timedelta(df_datetime['tenure_months'] * 30, unit='D')

# print("Sample with join_date:")
# print(df_datetime[['customer_id', 'tenure_months', 'join_date']].head())

# print("\nDatetime dtype:")
# print(df_datetime['join_date'].dtype)

# pd.to_timedelta(reference_date)

0   2026-04-09
1   2014-04-28
2   2025-01-03
3   2023-12-14
dtype: datetime64[ns]
0   9731 days
dtype: timedelta64[ns]
0   -124 days
dtype: timedelta64[ns]

In [42]:

print(pd.to_datetime(df_dates).dt.day)
print(pd.to_datetime(df_dates).dt.month)
print(pd.to_datetime(df_dates).dt.year)
print(pd.to_datetime(df_dates).dt.quarter)
print(pd.to_datetime(df_dates).dt.day_of_week)

0     9
1    28
2     3
3    14
dtype: int32
0     4
1     4
2     1
3    12
dtype: int32
0    2026
1    2014
2    2025
3    2023
dtype: int32
0    2
1    2
2    1
3    4
dtype: int32
0    3
1    0
2    4
3    3
dtype: int32

In [43]:
# Check for any missing values in a column

df_missing = pd.DataFrame( {"name":["kevin","devin", "nivin"], "age":[22,42, None] } )
num_missing_age_vals = df_missing["age"].isnull().sum()
print(num_missing_age_vals)

1

In [44]:
# replacing values in dataseries
series = pd.Series(["m","f","m","f","m"]);
series.replace({"m":"male","f":"female"})

0      male
1    female
2      male
3    female
4      male
dtype: object

In [45]:
df = pd.read_csv("abc.csv")

In [ ]:
# applying a function for all the values in a column
def grader(score):
    grade = "F"
    if(score >= 90):
        grade = "A"
    elif(score >= 80):
        grade = "B"
    elif(score >= 70):
        grade = "C"
    return grade

# but this way of applying is slower.
df['grade'] = df['science'].apply(grader)
df

  student  language  science  maths  history grade
0   kumar        90       56     34       34     F
1   kevin        10       34     32       67     F
2   sammy        90       23     12       32     F
3  janice        20       67     90       45     A
4   peter        30       56     45       65     F
5    prem        90       45     45       34     F
6  carrol        50       90     45       23     F

In [48]:
# grouping based on a column

In [51]:
df.groupby("grade")["grade"]